
name: Build Library
author: Crowdin

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x
          
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build -c Release --no-restore
      
      - name: Publish
        run: dotnet nuget push **\*.nupkg -s https://nuget.org -k ${{secrets.NUGET_KEY}}
      